TERMUX_PKG_HOMEPAGE='https://github.com/unhappychoice/gitlogue'
TERMUX_PKG_DESCRIPTION='A cinematic Git commit replay tool for the terminal, turning your Git history into a living, animated story.'
TERMUX_PKG_LICENSE='ISC'
TERMUX_PKG_MAINTAINER='@termux '
TERMUX_PKG_VERSION='0.3.0'
TERMUX_PKG_SRCURL=https://github.com/unhappychoice/gitlogue/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256='7346e59149f48c34f7b6c7777a6c02da342c27202c257dea86a5d20e6b3d8828'
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
